### ISSUE TITLE
Mac 版本迅雷3.1.1 safari 和chrome 都安装了插件，下载xcode 9.0 xip 启动不了迅雷

### ISSUE THREAD

**Issue by csc-EricWu** [TidleCao/MacThunder#2]
Mac 版本迅雷3.1.1 safari 和chrome 都安装了插件，下载xcode 9.0 xip 启动不了迅雷

**Comment by TidleCao** [comment]
浏览器插件暂时不支持xip后缀的文件拉起Mac迅雷。请手动复制链接创建下载任务
